name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  YUMEMI_API_KEY: ${{ secrets.YUMEMI_API_KEY }}
jobs:
  bun-test_and_e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencie
        run: bun install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Run test
        run: bun test
      - name: Run build
        run: bun run build
      - name: Run Playwright tests
        run: bunx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
